#!/bin/bash
setxkbmap -layout "us,ru" -option grp:alt_space_toggle &
bgs -z /usr/share/archlinux/wallpaper/archlinux-firestarter.jpg
spoon &
/usr/lib/notification-daemon-1.0/notification-daemon &
echo 'done'
